### PR TITLE
Add auth and profile page

### PR DESCRIPTION
**Pull request by OmKakatkar**
# Features

## Additions
* Auth context with toast notification
* Login and Sign Up form
* Test user credentials for Login and Sign Up
* Profile page for user data

### CODE REVIEW

**Review by rohit8686 — APPROVED** [review]
- Code looks clean and modular
- Suggestion : If invalid credentials are given while login, you could show error message

**Review by chanchal-panpaliya — COMMENTED** [review]
code looks clean with proper naming with good UI

need to check->
1st -> After registration, the first name and last name are not displayed.
image


2nd -> After the 1st time registered, logout. If I try to register again, the button is disabled. 
image

**Comment by OmKakatkar** [comment]
> * Code looks clean and modular
> * Suggestion : If invalid credentials are given while login, you could show error message

Thank You for the suggestion, the code has been updated accordingly

**Comment by OmKakatkar** [comment]
> code looks clean with proper naming with good UI
> 
> need to check-> 1st -> After registration, the first name and last name are not displayed. image
> 
> 2nd -> After the 1st time registered, logout. If I try to register again, the button is disabled.  image

Thank you for the review, the first issue has been solved.
The 2nd one is the intended feature, user must check the Term and Conditions box before proceeding to sign up

**Pull request merged**
